name: unicode_data
description: This library puts Unicode data in a format that can be programmatically manipulated.
version: 0.1.1
homepage: https://github.com/suragch/unicode_data
author: Suragch <studymongolian@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
