name: unicode_data
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/suragch/unicode_data
author: Suragch <studymongolian@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
