name: unicode_data
description: This library puts Unicode data in a format that can be programmatically manipulated.
version: 0.2.0-nullsafety.0
homepage: https://github.com/suragch/unicode_data

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.11
